input_file = "4_digit_display"

drill_in = open(input_file + ".drd",'r')
code_out = "./tap/" + input_file + "-drill.tap"
drill_out = open(code_out,'w')
feed_rate = "500"
drill_list = {}

drill_out.write("(Project " + input_file + " )\n")
drill_out.write("(generated by iStivi python script drill+mill_genarator.py)\n")
drill_out.write("G71 G90" + "\n") #metric, absolute coord
drill_out.write("F" + feed_rate + "\n")
drill_out.write("G0 Z5" + "\n")


line = drill_in.readline()
line = drill_in.readline()
while line != "%\n":
   m_find = line.find('M')
   tool_find = line.find('T')
   print(line)
   if m_find >= 0:
      print("command")
   if tool_find >= 0:
      tool_name = line[:3]
      tool_size = line[-7:-1]
      drill_list[tool_name] = tool_size
      drill_out.write("( " + tool_name + " : " + tool_size + " )\n")
   line = drill_in.readline()

for line in drill_in:
   x_start = line.find('X')
   y_start = line.find('Y')
   tool_set = line.find('T') 

   if tool_set == 0:
       drill_out.write("G0 Z20" + "\n")
       drill_out.write(line[:-1] + " M6 (" + line[:-1] + " " + drill_list[line[:-1]] + ")" + "\n")
   elif x_start > -1:
      x_pos = line[x_start+1:y_start]
      y_pos = line[y_start+1:]
      drill_out.write("G0 X" + x_pos[:-3] + "." + x_pos[-3:] + " Y" + y_pos[:-4] + "." + y_pos[-4:-1] + "\n")
      drill_out.write("G1 Z-2" + "\n")
   drill_out.write("G4 P0.1" + "\n")
   drill_out.write("G0 Z2" + "\n")

drill_out.write("M30" + "\n")

drill_in.close()
drill_out.close()

   
